const BG_SALMON = '#EE7777';
const AUTHOR = '#999999';
const TITLE_HEADER = '#424242';
const TITLE_CARD = '#333333';
const BORDER_COLOR = '#EEEEEE';
const SHADOW = '#DA6C6C';
const DESCRIPTOIN_CARD = '#666666';
const BG_WHITE = '#FFFFFF';


export default {
  BG_SALMON, TITLE_HEADER, BG_WHITE, SHADOW, TITLE_CARD, AUTHOR, DESCRIPTOIN_CARD, BORDER_COLOR,
};
